version: '3.9'
services:
  smtp_server:
    image: gessnerfl/fake-smtp-server
    container_name: readme_fake-smtp-server
    hostname: readme_fake-smtp-server
    ports:
      - ${FAKE_SMTP_PORT}:8025
      - ${FAKE_SMTP_UI_PORT}:8080

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: readme_rabbitmq
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  mongo_notifications:
    image: mongo:7.0
    container_name: readme_notifications_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_USER_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    command: mongod --port 27019
    ports:
      - ${MONGO_DB_PORT}:27019
    volumes:
      - mongo_notifications_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME} --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  mongo_notifications_ui:
    image: mongo-express:latest
    container_name: readme_notifications_mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_USER_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_USER_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_USER_PASSWORD}@mongo_notifications:${MONGO_DB_PORT}/

volumes:
   mongo_notifications_data:
