version: '3.9'
services:
  readme-customers-mongoDB:
    image: mongo:7.0
    container_name: readme-customers-mongo
    restart: always
    env_file:
      - .stage.env
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - readme-customers-data:/data/db
    networks:
      - readme-network
  readme-customers-app:
    image: readme-customers:1.0
    container_name: readme-customers-app
    depends_on:
      - readme-customers-mongoDB
    restart: always
    env_file:
      - .stage.env
    ports:
      - ${PORT}:5000
    networks:
      - readme-network
networks:
  readme-network:
    name: readme-network
    driver: bridge
volumes:
  readme-customers-data:
